
export enum STATE {
    EXTENSION_INACTIVE,
    COMMENTS_LOGGED_OUT,
    REGISTER,
    LOGIN,
    PW_RESET,
    COMMENTS_MEMBER,
    SETTINGS_MEMBER,
    COMMENTS_MODERATOR,
    MODERATION_MODERATOR,
    SETTINGS_MODERATOR,
    COMMENTS_ADMIN,
    SETTINGS_ADMIN,
    REPORTS_ADMIN,
    MODERATION_ADMIN
}